import { v7 as uuid } from 'uuid';
import {
  Category,
  LearningModule,
} from 'src/app/learning-module/types/learning-module.interface';

export const initialLearningModules: LearningModule[] = [
  {
    id: uuid(),
    title: 'Introduction to AI Ethics',
    category: Category.AI,
    estimatedMinutes: 30,
    completed: false,
  },
  {
    id: uuid(),
    title: 'Sustainable Software Development',
    category: Category.Sustainability,
    estimatedMinutes: 45,
    completed: true,
  },
  {
    id: uuid(),
    title: 'Advanced TypeScript Patterns',
    category: Category.DigitalSkills,
    estimatedMinutes: 60,
    completed: false,
  },
  {
    id: uuid(),
    title: 'Climate Change and Technology',
    category: Category.Sustainability,
    estimatedMinutes: 50,
    completed: false,
  },
  {
    id: uuid(),
    title: 'Generative AI Fundamentals',
    category: Category.AI,
    estimatedMinutes: 40,
    completed: true,
  },
  {
    id: uuid(),
    title: 'Cloud Security Best Practices',
    category: Category.DigitalSkills,
    estimatedMinutes: 70,
    completed: false,
  },
  {
    id: uuid(),
    title: 'AI in Healthcare',
    category: Category.AI,
    estimatedMinutes: 55,
    completed: false,
  },
  {
    id: uuid(),
    title: 'Green Computing Strategies',
    category: Category.Sustainability,
    estimatedMinutes: 35,
    completed: true,
  },
  {
    id: uuid(),
    title: 'Full-Stack Development with Node.js',
    category: Category.DigitalSkills,
    estimatedMinutes: 80,
    completed: false,
  },
  {
    id: uuid(),
    title: 'Ethical Implications of AI',
    category: Category.AI,
    estimatedMinutes: 45,
    completed: false,
  },
  {
    id: uuid(),
    title: 'Renewable Energy Technologies',
    category: Category.Sustainability,
    estimatedMinutes: 60,
    completed: true,
  },
  {
    id: uuid(),
    title: 'DevOps Essentials',
    category: Category.DigitalSkills,
    estimatedMinutes: 50,
    completed: false,
  },
  {
    id: uuid(),
    title: 'AI for Social Good',
    category: Category.AI,
    estimatedMinutes: 40,
    completed: false,
  },
  {
    id: uuid(),
    title: 'Sustainable Data Centers',
    category: Category.Sustainability,
    estimatedMinutes: 55,
    completed: true,
  },
  {
    id: uuid(),
    title: 'Responsive Web Design',
    category: Category.DigitalSkills,
    estimatedMinutes: 65,
    completed: false,
  },
  {
    id: uuid(),
    title: 'Machine Learning Basics',
    category: Category.AI,
    estimatedMinutes: 70,
    completed: false,
  },
  {
    id: uuid(),
    title: 'Eco-Friendly Software Practices',
    category: Category.Sustainability,
    estimatedMinutes: 30,
    completed: true,
  },
  {
    id: uuid(),
    title: 'Introduction to Cybersecurity',
    category: Category.DigitalSkills,
    estimatedMinutes: 75,
    completed: false,
  },
  {
    id: uuid(),
    title: 'AI-Driven Climate Solutions',
    category: Category.AI,
    estimatedMinutes: 50,
    completed: false,
  },
  {
    id: uuid(),
    title: 'Sustainability in Tech Industry',
    category: Category.Sustainability,
    estimatedMinutes: 45,
    completed: true,
  },
  {
    id: uuid(),
    title: 'JavaScript Frameworks Overview',
    category: Category.DigitalSkills,
    estimatedMinutes: 60,
    completed: false,
  },
  {
    id: uuid(),
    title: 'Natural Language Processing',
    category: Category.AI,
    estimatedMinutes: 55,
    completed: false,
  },
  {
    id: uuid(),
    title: 'Sustainable Mobile App Development',
    category: Category.Sustainability,
    estimatedMinutes: 40,
    completed: true,
  },
  {
    id: uuid(),
    title: 'Version Control with Git',
    category: Category.DigitalSkills,
    estimatedMinutes: 35,
    completed: false,
  },
  {
    id: uuid(),
    title: 'AI in Finance',
    category: Category.AI,
    estimatedMinutes: 65,
    completed: false,
  },
  {
    id: uuid(),
    title: 'Green Software Engineering',
    category: Category.Sustainability,
    estimatedMinutes: 50,
    completed: true,
  },
  {
    id: uuid(),
    title: 'Building RESTful APIs',
    category: Category.DigitalSkills,
    estimatedMinutes: 70,
    completed: false,
  },
  {
    id: uuid(),
    title: 'Computer Vision Fundamentals',
    category: Category.AI,
    estimatedMinutes: 45,
    completed: false,
  },
  {
    id: uuid(),
    title: 'Sustainability Metrics in IT',
    category: Category.Sustainability,
    estimatedMinutes: 60,
    completed: true,
  },
  {
    id: uuid(),
    title: 'Frontend Development with Angular',
    category: Category.DigitalSkills,
    estimatedMinutes: 80,
    completed: false,
  },
  {
    id: uuid(),
    title: 'Reinforcement Learning Basics',
    category: Category.AI,
    estimatedMinutes: 55,
    completed: false,
  },
  {
    id: uuid(),
    title: 'Sustainable IT Infrastructure',
    category: Category.Sustainability,
    estimatedMinutes: 35,
    completed: true,
  },
  {
    id: uuid(),
    title: 'Database Management Systems',
    category: Category.DigitalSkills,
    estimatedMinutes: 75,
    completed: false,
  },
  {
    id: uuid(),
    title: 'AI for Environmental Monitoring',
    category: Category.AI,
    estimatedMinutes: 50,
    completed: false,
  },
  {
    id: uuid(),
    title: 'Sustainability Reporting in Tech',
    category: Category.Sustainability,
    estimatedMinutes: 40,
    completed: true,
  },
  {
    id: uuid(),
    title: 'Introduction to Docker',
    category: Category.DigitalSkills,
    estimatedMinutes: 65,
    completed: false,
  },
  {
    id: uuid(),
    title: 'Deep Learning Overview',
    category: Category.AI,
    estimatedMinutes: 70,
    completed: false,
  },
  {
    id: uuid(),
    title: 'Energy-Efficient Coding Practices',
    category: Category.Sustainability,
    estimatedMinutes: 30,
    completed: true,
  },
  {
    id: uuid(),
    title: 'Agile Software Development',
    category: Category.DigitalSkills,
    estimatedMinutes: 55,
    completed: false,
  },
  {
    id: uuid(),
    title: 'AI in Education',
    category: Category.AI,
    estimatedMinutes: 60,
    completed: false,
  },
  {
    id: uuid(),
    title: 'Sustainable User Experience Design',
    category: Category.Sustainability,
    estimatedMinutes: 45,
    completed: true,
  },
  {
    id: uuid(),
    title: 'Microservices Architecture',
    category: Category.DigitalSkills,
    estimatedMinutes: 80,
    completed: false,
  },
  {
    id: uuid(),
    title: 'AI-Powered Robotics',
    category: Category.AI,
    estimatedMinutes: 50,
    completed: false,
  },
  {
    id: uuid(),
    title: 'Sustainability and Cloud Computing',
    category: Category.Sustainability,
    estimatedMinutes: 65,
    completed: true,
  },
  {
    id: uuid(),
    title: 'Testing and Debugging Techniques',
    category: Category.DigitalSkills,
    estimatedMinutes: 40,
    completed: false,
  },
];
